### ISSUE TITLE
Schematic diagram of equipment production

### ISSUE THREAD

**Issue by 931436690** [ankilab/AirwaySymptomDetection#1]
Hi,
we are very interested in your equipment, as mentioned in the article（The main unit of the NSA was a printed circuit board embedded with a one-axis accelerometer (BU-27135, Knowles Inc., IL, USA) and a custom amplification module to preprocess and transmit the signal to a recording device.)
Would you mind sharing your amplification module and device schematics? It is better to have a circuit diagram.
Thanks.

**Comment by rgroh1996** [comment]
Hi,

I am sorry, but we are not allowed to disclose details about the developed PCB.
